### ISSUE TITLE
Include an example of xw.sub as well

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/PythonVA#1]
And / or the `csv_file_to_new_table`
 - https://github.com/AutoActuary/aa-py-core/blob/fbb66158778382a844254e751d9aa7aaf2760682/aa_py_core/xl/xludfs.py#L201

**Comment by heetbeet** [comment]
I initially had the full aa-py-core in the distribution (kinda by accident since deploy-scripts cheekily installs it), and had to add this to remove it:
https://github.com/AutoActuary/PythonVA/blob/c668a6c75abd46760ced2be44bc779b8315f2c1d/scripts/pre-build.bat#L5

But I think it would be a good idea to add a bunch of good Excel stuff to the repo. But then it might even be more beneficial to split `aa_py_core.xl` out into something like `excel_tools` and just install the whole package. @rudolfbyker ?

**Comment by rudolfbyker** [comment]
Yes, the plan was always to split up aa-py-core when it grows too big. We
could have multiple cores. I think the best division would be along the
lines of the folders inside aa-py-core. We shoould keep aa-py-core, but
just e.g. extract runner-py-core from it. Then runner-py-core depends on
aa-py-core, and things that use aa-py-core directly won't include runner
source code. Etcetera...

**Comment by malankriel** [comment]
Ag julle is sulke champs!
